### ISSUE TITLE
Xamarin Forms UWP App Fails to re-login after initial Login

### ISSUE THREAD

**Issue by james1301** [Azure-Samples/active-directory-b2c-xamarin-native#60]
I am trying to use the sample app, but the UWP version, after originally signing in, now fails whenever I try to sign in again with the error at the bottom.

The iOS app does not encounter this issue, not tried Android. I am running on the latest Windows (1803). In an attempt to remedy I have tried to update all nugets, make UWP target version 1803. Then have even tried upgrading all nuget componets to the latest preview version but still no change.

Not sure what I am missing if the iOS one runs fine.

Error in  UWP App:

{Microsoft.Identity.Client.MsalServiceException: Returned user identifier does not match the sent user identifier
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SaveTokenResponseToCache()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.PostTokenRequest()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenForUserCommonAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TodoAzure.AuthenticationProvider.<LoginAsync>d__9.MoveNext()
	ErrorCode: user_mismatch
	StatusCode: 0
	Claims: }

**Comment by jennyf19** [comment]
@james1301 Sorry to have missed this issue. The problem you encountered is from the cache not clearing. so if, for example, you logged in to your UWP app with the FB account, then closed the app, and relaunched and tried to log in with a Google account, you would ge the user mismatch error. This was resolved in [MSALv.2.01-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-V2.0.1). 

I'm closing this issue, as the fix has been out in MSAL for some time, but feel free to reopen or respond if you encounter other issues. Thanks.
